// app/sunnah/data.ts

export interface Sunnah {
    id: number;
    title: string;
    desc: string;
    book: string;
    num: string;
    points: number;
    category: string;
  }

  export const SUNNAH_LIBRARY: Sunnah[] = [
    { id: 1, title: "Dusting the Bed", desc: "Dust the bed three times before sleeping.", book: "Bukhari", num: "6320", points: 20, category: "Night" },
    { id: 2, title: "Cheerfulness", desc: "Meeting your brother with a cheerful face.", book: "Tirmidhi", num: "1956", points: 15, category: "General" },
    { id: 3, title: "Sleeping on Right Side", desc: "Lie on the right side with hand under cheek.", book: "Bukhari", num: "247", points: 25, category: "Night" },
    { id: 4, title: "Using the Miswak", desc: "Cleanse mouth before every prayer.", book: "Muslim", num: "252", points: 30, category: "General" },
    { id: 5, title: "Sitting While Drinking", desc: "Drinking in three slow breaths while sitting.", book: "Muslim", num: "2024", points: 20, category: "General" },
    { id: 6, title: "Morning Dhikr", desc: "Recite 'Alhamdulillah' immediately upon waking.", book: "Bukhari", num: "6312", points: 15, category: "Morning" },
    { id: 7, title: "Right Foot Entry", desc: "Enter the Masjid or home with the right foot.", book: "Bukhari", num: "426", points: 10, category: "Masjid" },
    { id: 8, title: "Clearing the Path", desc: "Remove an obstacle or harm from the walkway.", book: "Muslim", num: "1914", points: 40, category: "General" },
    { id: 9, title: "Wudu Before Sleep", desc: "Perform ablution before going to bed.", book: "Bukhari", num: "247", points: 50, category: "Night" },
    { id: 10, title: "The Handshake", desc: "Shake hands when meeting a fellow Muslim.", book: "Abu Dawud", num: "5212", points: 20, category: "Social" },
    { id: 11, title: "Greeting Children", desc: "Initiate Salaam to children to teach them.", book: "Muslim", num: "2168", points: 25, category: "Social" },
    { id: 12, title: "The 1/3 Rule", desc: "Fill 1/3 with food, 1/3 with water, 1/3 for air.", book: "Ibn Majah", num: "3349", points: 40, category: "Food" },
    { id: 13, title: "Sneezing Etiquette", desc: "Say Alhamdulillah and cover face.", book: "Bukhari", num: "6224", points: 15, category: "General" },
    { id: 14, title: "Starting with Right", desc: "Putting on the right shoe/sleeve first.", book: "Bukhari", num: "5855", points: 10, category: "Clothing" },
    { id: 15, title: "Dua for Parents", desc: "Ask Allah for mercy for parents during the day.", book: "Quran", num: "17:24", points: 30, category: "Dua" },
    { id: 16, title: "Licking Fingers", desc: "Lick fingers after eating before wiping them.", book: "Muslim", num: "2031", points: 20, category: "Food" },
    { id: 17, title: "Ablution before Sleep", desc: "Performing Wudu before going to bed.", book: "Bukhari", num: "247", points: 45, category: "Night" },
    { id: 18, title: "Istikharah", desc: "Consulting Allah in all important matters.", book: "Bukhari", num: "1166", points: 60, category: "Dua" },
    { id: 19, title: "Walking Barefoot", desc: "Occasionally walking barefoot as the Prophet did.", book: "Abu Dawud", num: "4160", points: 20, category: "General" },
    { id: 20, title: "Shortening the Khutbah", desc: "Keeping talks/reminders concise and meaningful.", book: "Muslim", num: "869", points: 25, category: "Speech" },
    { id: 21, title: "Visiting the Sick", desc: "Visiting a person who is unwell.", book: "Bukhari", num: "5650", points: 70, category: "Social" },
    { id: 22, title: "Sitting for Qul", desc: "Reciting 3 Quls into hands and rubbing over body.", book: "Bukhari", num: "5017", points: 30, category: "Night" },
    { id: 23, title: "Gift Giving", desc: "Give gifts to one another to increase love.", book: "Bukhari (Adab)", num: "594", points: 50, category: "Social" },
    { id: 24, title: "Using Fragrance", desc: "Applying Atar/Perfume (for men in public).", book: "Bukhari", num: "880", points: 15, category: "General" },
    { id: 25, title: "Picking up Fallen Food", desc: "Clean and eat food that falls; don't leave for Shaitan.", book: "Muslim", num: "2033", points: 35, category: "Food" },
    { id: 26, title: "Pointing with Finger", desc: "Using the index finger to point, not the whole hand.", book: "Muslim", num: "534", points: 10, category: "Speech" },
    { id: 27, title: "Sitting Cross-legged", desc: "Sitting 'Al-Ihtiba' or cross-legged in the Masjid.", book: "Abu Dawud", num: "4846", points: 15, category: "Masjid" },
    { id: 28, title: "The Siesta (Qaylulah)", desc: "Taking a short midday nap to aid night prayer.", book: "Tabarani", num: "28", points: 40, category: "Day" },
    { id: 29, title: "Dua after Eating", desc: "Reciting Alhamdulillah after finishing a meal.", book: "Tirmidhi", num: "3458", points: 20, category: "Food" },
    { id: 30, title: "Entering with Right Foot", desc: "Enter the Masjid with the right foot.", book: "Bukhari", num: "426", points: 10, category: "Masjid" },
    { id: 31, title: "Leaving with Left Foot", desc: "Exit the Masjid with the left foot.", book: "Bukhari", num: "426", points: 10, category: "Masjid" },
    { id: 32, title: "Tahiyyatul Masjid", desc: "Praying 2 Rakaats upon entering the Masjid.", book: "Bukhari", num: "444", points: 50, category: "Prayer" },
    { id: 33, title: "Repeating the Adhan", desc: "Repeating the words after the Mu'adhin.", book: "Bukhari", num: "611", points: 30, category: "Prayer" },
    { id: 34, title: "Dua after Adhan", desc: "Asking for 'Al-Wasilah' for the Prophet.", book: "Bukhari", num: "614", points: 35, category: "Prayer" },
    { id: 35, title: "Shaking out Clothing", desc: "Checking clothes/shoes before putting them on.", book: "Bukhari", num: "6320", points: 15, category: "Clothing" },
    { id: 36, title: "Honoring the Guest", desc: "Whoever believes in Allah should honor their guest.", book: "Bukhari", num: "6018", points: 60, category: "Social" },
    { id: 37, title: "Truthful Speech", desc: "Avoid lying even when joking.", book: "Tirmidhi", num: "1990", points: 55, category: "Speech" },
    { id: 38, title: "Lowering the Gaze", desc: "Avoiding looking at the forbidden.", book: "Quran", num: "24:30", points: 80, category: "General" },
    { id: 39, title: "Dua before Toilet", desc: "Asking protection from male/female devils.", book: "Bukhari", num: "142", points: 20, category: "General" },
    { id: 40, title: "Leaving with Right", desc: "Exiting the bathroom with the right foot.", book: "Tirmidhi", num: "7", points: 10, category: "General" },
    { id: 41, title: "Ghufranak", desc: "Saying 'I ask Your forgiveness' after bathroom.", book: "Abu Dawud", num: "30", points: 15, category: "General" },
    { id: 42, title: "Dua when Dressing", desc: "Acknowledging Allah as the Provider of clothes.", book: "Abu Dawud", num: "4023", points: 25, category: "Clothing" },
    { id: 43, title: "Cupping (Hijama)", desc: "Applying the Sunnah of healing.", book: "Bukhari", num: "5678", points: 100, category: "Health" },
    { id: 44, title: "Honey for Healing", desc: "Using honey as a shifa (cure).", book: "Bukhari", num: "5677", points: 30, category: "Health" },
    { id: 45, title: "Black Seed", desc: "Incorporating Kalonji into your diet.", book: "Bukhari", num: "5688", points: 30, category: "Health" },
    { id: 46, title: "Drinking in Intervals", desc: "Don't drink the whole glass in one go.", book: "Bukhari", num: "5631", points: 20, category: "Food" },
    { id: 47, title: "Feeding the Poor", desc: "Giving food to those in need.", book: "Bukhari", num: "12", points: 90, category: "Social" },
    { id: 48, title: "Helping the Widow", desc: "Striving for the widow and the poor.", book: "Bukhari", num: "5353", points: 100, category: "Social" },
    { id: 49, title: "Gentleness (Rifq)", desc: "Allah loves gentleness in all matters.", book: "Bukhari", num: "6927", points: 50, category: "Speech" },
    { id: 50, title: "Planting a Tree", desc: "Planting a tree that others/animals eat from.", book: "Bukhari", num: "2320", points: 75, category: "General" },
    { id: 51, title: "The Siwak before Salah", desc: "Importance of oral hygiene for prayer.", book: "Bukhari", num: "887", points: 30, category: "General" },
    { id: 52, title: "Covering Vessels", desc: "Covering water/food containers at night.", book: "Muslim", num: "2012", points: 25, category: "Night" },
    { id: 53, title: "Dua for New Moon", desc: "Asking for peace and faith at month start.", book: "Tirmidhi", num: "3451", points: 40, category: "Dua" },
    { id: 54, title: "Shortening Prayer in Travel", desc: "Accepting the concession of Allah.", book: "Bukhari", num: "1081", points: 40, category: "Travel" },
    { id: 55, title: "Seeking Forgiveness (Istighfar)", desc: "Asking for forgiveness 70-100 times daily.", book: "Bukhari", num: "6307", points: 50, category: "Dua" },
    { id: 56, title: "Dua for Rain", desc: "Praying 'Salatul Istisqa' during drought.", book: "Bukhari", num: "1013", points: 60, category: "Dua" },
    { id: 57, title: "Dua after Wudu", desc: "Reciting the Shahadah after finishing Wudu.", book: "Muslim", num: "234", points: 35, category: "Prayer" },
    { id: 58, title: "Fasting Mondays", desc: "Fasting on the day the Prophet was born.", book: "Muslim", num: "1162", points: 100, category: "Fasting" },
    { id: 59, title: "Fasting Thursdays", desc: "Fasting when deeds are presented to Allah.", book: "Tirmidhi", num: "747", points: 100, category: "Fasting" },
    { id: 60, title: "Fasting White Days", desc: "Fasting the 13th, 14th, and 15th of the month.", book: "Abu Dawud", num: "2449", points: 150, category: "Fasting" },
    { id: 61, title: "Dua for Clothing", desc: "Saying the prayer for wearing a new garment.", book: "Tirmidhi", num: "1767", points: 25, category: "Clothing" },
    { id: 62, title: "Lying on Right Side", desc: "Resting briefly on the right side after Fajr sunnah.", book: "Bukhari", num: "1160", points: 35, category: "Morning" },
    { id: 63, title: "Istighfar 100 Times", desc: "Seeking forgiveness 100 times throughout the day.", book: "Muslim", num: "2702", points: 50, category: "Dhikr" },
    { id: 64, title: "Prophetic Bath (Ghusl)", desc: "Performing Ghusl on Friday as a sunnah.", book: "Bukhari", num: "877", points: 60, category: "Friday" },
    { id: 65, title: "Walking to Prayer", desc: "Walking to the Masjid for congregational prayer.", book: "Bukhari", num: "662", points: 45, category: "Masjid" },
    { id: 66, title: "Covering Sneeze", desc: "Covering the mouth with hands or cloth when sneezing.", book: "Tirmidhi", num: "2735", points: 15, category: "General" },
    { id: 67, title: "Small Steps", desc: "Taking small steps to the Masjid to increase reward.", book: "Muslim", num: "666", points: 20, category: "Masjid" },
    { id: 68, title: "Sitting in Tashahhud", desc: "Placing hands correctly during the sitting of prayer.", book: "Muslim", num: "580", points: 15, category: "Prayer" },
    { id: 69, title: "Tahajjud Prayer", desc: "Waking up in the last third of the night.", book: "Bukhari", num: "1145", points: 150, category: "Night" },
    { id: 70, title: "Dua for Rain", desc: "Asking Allah for rain during a drought.", book: "Bukhari", num: "1013", points: 40, category: "Dua" },
    { id: 71, title: "Cleaning Vessels", desc: "Not leaving dirty dishes uncovered overnight.", book: "Muslim", num: "2012", points: 20, category: "Kitchen" },
    { id: 72, title: "Dua for Travel", desc: "Reciting the prayer for safety when traveling.", book: "Muslim", num: "1342", points: 30, category: "Travel" },
    { id: 73, title: "Fasting 3 Days", desc: "Fasting any three days of every month.", book: "Bukhari", num: "1981", points: 120, category: "Fasting" },
    { id: 74, title: "Honoring Parents", desc: "Being kind and soft in speech to parents.", book: "Quran", num: "17:23", points: 100, category: "Social" },
    { id: 75, title: "Feeding Neighbors", desc: "Sharing a portion of your meal with neighbors.", book: "Muslim", num: "2625", points: 55, category: "Social" },
    { id: 76, title: "Dua after Eating", desc: "Praising Allah after finishing your food.", book: "Tirmidhi", num: "3458", points: 20, category: "Food" },
    { id: 77, title: "Smiling to Siblings", desc: "Spreading joy within the household.", book: "Tirmidhi", num: "1956", points: 20, category: "General" },
    { id: 78, title: "Reciting Ayatul Kursi", desc: "Reciting it after every obligatory prayer.", book: "Nasa'i", num: "9928", points: 40, category: "Dhikr" },
    { id: 79, title: "Washing Hands", desc: "Washing hands before and after meals.", book: "Abu Dawud", num: "3761", points: 15, category: "Food" },
    { id: 80, title: "SubhanAllah x33", desc: "Reciting tasbih after Fard prayer.", book: "Muslim", num: "597", points: 35, category: "Dhikr" },
    { id: 81, title: "Alhamdulillah x33", desc: "Reciting tahmid after Fard prayer.", book: "Muslim", num: "597", points: 35, category: "Dhikr" },
    { id: 82, title: "Allahu Akbar x34", desc: "Reciting takbir after Fard prayer.", book: "Muslim", num: "597", points: 35, category: "Dhikr" },
    { id: 83, title: "Dua for Market", desc: "Reciting the prayer when entering a marketplace.", book: "Tirmidhi", num: "3428", points: 80, category: "Dua" },
    { id: 84, title: "Gentle Correction", desc: "Correcting someone's mistake without shaming.", book: "Bukhari", num: "6035", points: 45, category: "Speech" },
    { id: 85, title: "Checking for Pins", desc: "Checking shoes for insects or stones before wear.", book: "Abu Dawud", num: "4139", points: 10, category: "General" },
    { id: 86, title: "Kindness to Animals", desc: "Providing water or food to a stray animal.", book: "Bukhari", num: "2363", points: 90, category: "Social" },
    { id: 87, title: "Dua for New Clothes", desc: "Acknowledging the Provider of the garment.", book: "Abu Dawud", num: "4023", points: 25, category: "Clothing" },
    { id: 88, title: "Speaking Good", desc: "Saying a good word or remaining silent.", book: "Bukhari", num: "6018", points: 50, category: "Speech" },
    { id: 89, title: "Avoiding Ghibah", desc: "Actively stopping backbiting in a conversation.", book: "Muslim", num: "2589", points: 70, category: "Speech" },
    { id: 90, title: "Dua for Anger", desc: "Saying A'udhu billah when feeling angry.", book: "Bukhari", num: "6115", points: 30, category: "Self" },
    { id: 91, title: "Dua for New Moon", desc: "Praying for security and faith at the sight of the crescent.", book: "Tirmidhi", num: "3451", points: 40, category: "Dua" },
    { id: 92, title: "The Siesta (Qaylulah)", desc: "Taking a short midday nap to prepare for night prayer.", book: "Tabarani", num: "28", points: 30, category: "General" },
    { id: 93, title: "Using the Right Hand", desc: "Using the right hand for eating, drinking, and giving.", book: "Bukhari", num: "5376", points: 20, category: "General" },
    { id: 94, title: "Shaking out Shoes", desc: "Checking shoes before putting them on for insects/dirt.", book: "Abu Dawud", num: "4139", points: 15, category: "General" },
    { id: 95, title: "Wudu before Ghusl", desc: "Performing ablution before the full ritual bath.", book: "Bukhari", num: "248", points: 35, category: "Purity" },
    { id: 96, title: "Dua after Adhan", desc: "Asking for the Prophet's intercession after the call.", book: "Bukhari", num: "614", points: 30, category: "Prayer" },
    { id: 97, title: "Smiling to Parents", desc: "A look of mercy at parents is a rewarded act.", book: "Quran", num: "17:23", points: 50, category: "Social" },
    { id: 98, title: "Dua when it Rains", desc: "Saying 'Allahumma sayyiban nafi’an' during rain.", book: "Bukhari", num: "1032", points: 25, category: "Dua" },
    { id: 99, title: "Tahiyyatul Masjid", desc: "Praying 2 units upon entering any Masjid.", book: "Bukhari", num: "444", points: 45, category: "Prayer" },
    { id: 100, title: "Closing the Mouth", desc: "Covering the mouth with the hand while yawning.", book: "Muslim", num: "2995", points: 15, category: "General" },
    { id: 101, title: "Visiting Neighbors", desc: "Checking on the welfare of those living near you.", book: "Bukhari", num: "6016", points: 60, category: "Social" },
    { id: 102, title: "Dua for Sickness", desc: "Reciting 'Adhhibil-bas' when visiting the ill.", book: "Bukhari", num: "5675", points: 50, category: "Dua" },
    { id: 103, title: "Shortening the Khutbah", desc: "Keeping reminders concise so they are remembered.", book: "Muslim", num: "869", points: 30, category: "Speech" },
    { id: 104, title: "Planting a Tree", desc: "The reward continues as long as creatures eat from it.", book: "Bukhari", num: "2320", points: 80, category: "General" },
    { id: 105, title: "Truthful Trading", desc: "Being honest in buying and selling transactions.", book: "Bukhari", num: "2079", points: 70, category: "Business" },
    { id: 106, title: "Dua for Debts", desc: "Asking Allah for relief from the burden of debt.", book: "Tirmidhi", num: "3563", points: 40, category: "Dua" },
    { id: 107, title: "Helping at Home", desc: "The Prophet used to stitch clothes and help his family.", book: "Bukhari", num: "676", points: 90, category: "Social" },
    { id: 108, title: "Dua for Traveling", desc: "Saying 'Subhanalladhi sakhara' when departing.", book: "Muslim", num: "1342", points: 35, category: "Travel" },
    { id: 109, title: "Greeting Everyone", desc: "Giving Salaam to those you know and those you don't.", book: "Bukhari", num: "12", points: 40, category: "Social" },
    { id: 110, title: "Dua for Morning", desc: "Saying 'Allahumma bika asbahna' at dawn.", book: "Tirmidhi", num: "3391", points: 30, category: "Morning" },
    { id: 111, title: "Avoiding Quarrels", desc: "Leaving an argument even if you are right.", book: "Abu Dawud", num: "4800", points: 100, category: "Speech" },
    { id: 112, title: "Dua for Forgiveness", desc: "Saying 'Astaghfirullah' 3 times after Fard prayer.", book: "Muslim", num: "591", points: 20, category: "Prayer" },
    { id: 113, title: "Honoring Guests", desc: "Belief in Allah is tied to honoring the guest.", book: "Bukhari", num: "6018", points: 55, category: "Social" },
    { id: 114, title: "Dua before Sleep", desc: "Reciting 'Bismika Allahumma amutu wa ahya'.", book: "Bukhari", num: "6312", points: 20, category: "Night" },
    { id: 115, title: "Lowering the Gaze", desc: "Preserving the purity of the heart from the forbidden.", book: "Quran", num: "24:30", points: 85, category: "General" },
    { id: 116, title: "Fasting Mondays", desc: "Reviving the fast of the day the Prophet was born.", book: "Muslim", num: "1162", points: 100, category: "Fasting" },
    { id: 117, title: "Walking Barefoot", desc: "Walking without shoes occasionally as a sunnah.", book: "Abu Dawud", num: "4160", points: 20, category: "General" },
    { id: 118, title: "Dua after Wudu", desc: "Reciting the Shahadah to open the 8 gates of Jannah.", book: "Muslim", num: "234", points: 40, category: "Purity" },
    { id: 119, title: "Kindness to Widows", desc: "Striving to help those who have lost their spouses.", book: "Bukhari", num: "5353", points: 120, category: "Social" },
    { id: 120, title: "Saying Alhamdulillah", desc: "Acknowledging Allah's favor after sneezing.", book: "Bukhari", num: "6224", points: 15, category: "General" },
    { id: 121, title: "Dua for Parents", desc: "Praying for mercy for parents as they raised you when small.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
    { id: 122, title: "The Handshake", desc: "Sins fall like leaves when two Muslims shake hands.", book: "Abu Dawud", num: "5212", points: 25, category: "Social" },
    { id: 123, title: "Using the Miswak", desc: "Using the tooth-stick before every prayer.", book: "Muslim", num: "252", points: 30, category: "General" },
    { id: 124, title: "Sneezing Manners", desc: "Covering the face and lowering the voice.", book: "Tirmidhi", num: "2735", points: 15, category: "General" },
    { id: 125, title: "Licking the Fingers", desc: "Licking the fingers after eating to catch the barakah.", book: "Muslim", num: "2031", points: 20, category: "Food" },
    { id: 126, title: "Dua after Eating", desc: "Praising Allah after completing a meal.", book: "Tirmidhi", num: "3458", points: 20, category: "Food" },
    { id: 127, title: "Entering with Right", desc: "Step into the Masjid with the right foot.", book: "Bukhari", num: "426", points: 10, category: "Masjid" },
    { id: 128, title: "Leaving with Left", desc: "Exit the Masjid with the left foot.", book: "Bukhari", num: "426", points: 10, category: "Masjid" },
    { id: 129, title: "Istikharah", desc: "Asking Allah for guidance in decisions.", book: "Bukhari", num: "1166", points: 60, category: "Prayer" },
    { id: 130, title: "Truthful Speech", desc: "Avoiding lying even while joking.", book: "Tirmidhi", num: "1990", points: 50, category: "Speech" },
    { id: 131, title: "Dua for Clothes", desc: "Thanking Allah when putting on new garments.", book: "Abu Dawud", num: "4023", points: 25, category: "Clothing" },
    { id: 132, title: "Visiting the Sick", desc: "70,000 angels pray for one who visits the ill.", book: "Tirmidhi", num: "969", points: 80, category: "Social" },
    { id: 133, title: "Dua for Toilets", desc: "Entering with the left foot and reciting the dua.", book: "Bukhari", num: "142", points: 20, category: "General" },
    { id: 134, title: "Dua for Exiting", desc: "Exiting the toilet with the right foot and saying Ghufranak.", book: "Tirmidhi", num: "7", points: 20, category: "General" },
    { id: 135, title: "Shaking out Clothes", desc: "Checking clothes for harm before wearing.", book: "Bukhari", num: "6320", points: 15, category: "Clothing" },
    { id: 136, title: "Morning Dhikr", desc: "Saying 'SubhanAllah wa bihamdihi' 100 times.", book: "Muslim", num: "2691", points: 50, category: "Dhikr" },
    { id: 137, title: "Honoring Neighbors", desc: "Not causing harm to those living nearby.", book: "Bukhari", num: "6016", points: 65, category: "Social" },
    { id: 138, title: "Giving Gifts", desc: "Exchange gifts to increase mutual love.", book: "Bukhari (Adab)", num: "594", points: 55, category: "Social" },
    { id: 139, title: "Dua after Adhan", desc: "Sending blessings on the Prophet after the call.", book: "Muslim", num: "384", points: 35, category: "Prayer" },
    { id: 140, title: "Sitting while Drinking", desc: "The Prophet forbade drinking while standing.", book: "Muslim", num: "2024", points: 25, category: "General" },
    { id: 141, title: "Greeting Children", desc: "The Prophet used to initiate Salaam to kids.", book: "Muslim", num: "2168", points: 30, category: "Social" },
    { id: 142, title: "Removing Obstacles", desc: "Clearing the path for others as a form of charity.", book: "Muslim", num: "1914", points: 45, category: "General" },
    { id: 143, title: "Cupping (Hijama)", desc: "Applying the prophetic medicine for healing.", book: "Bukhari", num: "5678", points: 100, category: "Health" },
    { id: 144, title: "Using Honey", desc: "Using honey for its healing properties.", book: "Bukhari", num: "5677", points: 35, category: "Health" },
    { id: 145, title: "Tahajjud Prayer", desc: "Praying in the middle of the night.", book: "Bukhari", num: "1145", points: 150, category: "Prayer" },
    { id: 146, title: "Shortening Reminders", desc: "Keeping spiritual talks brief and impactful.", book: "Muslim", num: "869", points: 30, category: "Speech" },
    { id: 147, title: "Dua for Travel", desc: "Saying the dua for riding a vehicle.", book: "Muslim", num: "1342", points: 35, category: "Travel" },
    { id: 148, title: "Fasting Thursdays", desc: "Fasting on the day deeds are raised.", book: "Tirmidhi", num: "747", points: 100, category: "Fasting" },
    { id: 149, title: "Dua for Rain", desc: "Asking for beneficial rain during dry spells.", book: "Bukhari", num: "1013", points: 45, category: "Dua" },
    { id: 150, title: "Walking to Masjid", desc: "Reward for every step taken towards prayer.", book: "Bukhari", num: "662", points: 50, category: "Masjid" },
    { id: 151, title: "Drinking in 3 breaths", desc: "Avoid gulping water in one breath.", book: "Muslim", num: "2024", points: 20, category: "Food" },
    { id: 152, title: "Using Siwak at night", desc: "Using the miswak if you wake up during the night.", book: "Bukhari", num: "245", points: 35, category: "Night" },
    { id: 153, title: "Seeking knowledge", desc: "Spending time reading or listening to a religious talk.", book: "Tirmidhi", num: "2646", points: 70, category: "General" },
    { id: 154, title: "Kindness to spouses", desc: "Helping your family with household chores.", book: "Bukhari", num: "676", points: 60, category: "Social" },
    { id: 155, title: "Covering the mouth", desc: "Placing your hand over your mouth when yawning.", book: "Muslim", num: "2995", points: 15, category: "General" },
    { id: 156, title: "Dua for the Ummah", desc: "Asking Allah to forgive all believing men and women.", book: "Tabarani", num: "2118", points: 50, category: "Dua" },
    { id: 157, title: "Avoiding waste", desc: "Not wasting water even if you are at a running river.", book: "Ibn Majah", num: "425", points: 40, category: "General" },
    { id: 158, title: "Wearing White", desc: "Choosing white garments as they are among the best.", book: "Tirmidhi", num: "994", points: 30, category: "Clothing" },
    { id: 159, title: "Dua before sleeping", desc: "Reciting 'Bismika Allahumma amutu wa ahya'.", book: "Bukhari", num: "6312", points: 20, category: "Night" },
    { id: 160, title: "Tahiyatul Masjid", desc: "Praying 2 units before sitting in the Masjid.", book: "Bukhari", num: "444", points: 50, category: "Prayer" },
    { id: 161, title: "Dua for protection", desc: "Reciting the 3 Quls (Ikhlas, Falaq, Nas) daily.", book: "Tirmidhi", num: "3575", points: 40, category: "Dua" },
    { id: 162, title: "Starting with Salaam", desc: "Giving Salaam before starting a conversation.", book: "Tirmidhi", num: "2699", points: 25, category: "Social" },
    { id: 163, title: "Lowering the voice", desc: "Speaking softly and avoiding shouting.", book: "Quran", num: "31:19", points: 30, category: "Speech" },
    { id: 164, title: "Dua after waking", desc: "Saying 'Alhamdulillahilladhi ahyana...'", book: "Bukhari", num: "6312", points: 25, category: "Morning" },
    { id: 165, title: "Honoring the elderly", desc: "Showing respect and giving way to the elders.", book: "Tirmidhi", num: "1915", points: 55, category: "Social" },
    { id: 166, title: "Visiting the graveyard", desc: "Reminding oneself of the afterlife.", book: "Muslim", num: "977", points: 60, category: "General" },
    { id: 167, title: "Using the right hand", desc: "Eating and drinking only with the right hand.", book: "Muslim", num: "2020", points: 20, category: "Food" },
    { id: 168, title: "Dua for anxiety", desc: "Reciting 'Allahumma inni a'udhu bika minal-hammi'.", book: "Bukhari", num: "2893", points: 45, category: "Dua" },
    { id: 169, title: "Fasting 13, 14, 15", desc: "Fasting the white days of the lunar month.", book: "Nasa'i", num: "2420", points: 150, category: "Fasting" },
    { id: 170, title: "Dua for mirrors", desc: "Asking Allah for good character when seeing yourself.", book: "Ahmad", num: "24392", points: 20, category: "General" },
    { id: 171, title: "Feeding animals", desc: "Being merciful to cats, birds, or other animals.", book: "Bukhari", num: "3467", points: 40, category: "Social" },
    { id: 172, title: "Keeping promises", desc: "Fulfilling an oath or a promise made to someone.", book: "Bukhari", num: "33", points: 80, category: "General" },
    { id: 173, title: "Dua for rain", desc: "Saying 'Allahumma sayyiban nafi'an' when it rains.", book: "Bukhari", num: "1032", points: 20, category: "Dua" },
    { id: 174, title: "Praising the cook", desc: "Never criticizing food; if you like it, eat it.", book: "Bukhari", num: "5409", points: 35, category: "Food" },
    { id: 175, title: "Walking to Masjid", desc: "Taking steps to the mosque for congregational prayer.", book: "Bukhari", num: "662", points: 50, category: "Masjid" },
    { id: 176, title: "Reciting Surah Mulk", desc: "Reading Surah Mulk every night before sleep.", book: "Tirmidhi", num: "2891", points: 100, category: "Night" },
    { id: 177, title: "Friday Ghusl", desc: "Taking a bath specifically for the Friday prayer.", book: "Bukhari", num: "877", points: 60, category: "Friday" },
    { id: 178, title: "Dua for entering home", desc: "Saying Bismillah when entering your house.", book: "Muslim", num: "2018", points: 25, category: "General" },
    { id: 179, title: "Tying the camel", desc: "Taking necessary precautions then trusting Allah.", book: "Tirmidhi", num: "2517", points: 50, category: "General" },
    { id: 180, title: "Sleeping in Wudu", desc: "Being in a state of purity when sleeping.", book: "Bukhari", num: "247", points: 60, category: "Night" },
    { id: 181, title: "Dua for Rain", desc: "Saying 'Allahumma sayyiban nafi'an' when it rains.", book: "Bukhari", num: "1032", points: 20, category: "Dua" },
  { id: 182, title: "Praising the cook", desc: "Never criticizing food; if you like it, eat it.", book: "Bukhari", num: "5409", points: 35, category: "Food" },
  { id: 183, title: "Walking to Masjid", desc: "Taking steps to the mosque for congregational prayer.", book: "Bukhari", num: "662", points: 50, category: "Masjid" },
  { id: 184, title: "Reciting Surah Mulk", desc: "Reading Surah Mulk every night before sleep.", book: "Tirmidhi", num: "2891", points: 100, category: "Night" },
  { id: 185, title: "Friday Ghusl", desc: "Taking a bath specifically for the Friday prayer.", book: "Bukhari", num: "877", points: 60, category: "Friday" },
  { id: 186, title: "Dua for entering home", desc: "Saying Bismillah when entering your house.", book: "Muslim", num: "2018", points: 25, category: "General" },
  { id: 187, title: "Tying the camel", desc: "Taking necessary precautions then trusting Allah.", book: "Tirmidhi", num: "2517", points: 50, category: "General" },
  { id: 188, title: "Sleeping in Wudu", desc: "Being in a state of purity when sleeping.", book: "Bukhari", num: "247", points: 60, category: "Night" },
  { id: 189, title: "Dua for Parents", desc: "Supplicating for them after every prayer.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
  { id: 190, title: "Cleaning the Siwak", desc: "Washing the miswak after each use.", book: "Abu Dawud", num: "52", points: 15, category: "General" },
  { id: 191, title: "Dua when sneezing", desc: "Saying 'Alhamdulillah' after a sneeze.", book: "Bukhari", num: "6224", points: 10, category: "General" },
  { id: 192, title: "Replying to sneeze", desc: "Saying 'YarhamukAllah' to a sneezing Muslim.", book: "Bukhari", num: "6224", points: 15, category: "General" },
  { id: 193, title: "Using right hand", desc: "Always giving and receiving with the right hand.", book: "Ibn Majah", num: "3266", points: 20, category: "General" },
  { id: 194, title: "Tahiyyatul Wudu", desc: "Praying 2 units immediately after making Wudu.", book: "Bukhari", num: "160", points: 50, category: "Prayer" },
  { id: 195, title: "Dua for travel", desc: "Saying 'Allahu Akbar' when going uphill while traveling.", book: "Bukhari", num: "2993", points: 25, category: "Travel" },
  { id: 196, title: "Dua for descending", desc: "Saying 'SubhanAllah' when going downhill while traveling.", book: "Bukhari", num: "2993", points: 25, category: "Travel" },
  { id: 197, title: "Istighfar", desc: "Seeking forgiveness 70 times a day.", book: "Bukhari", num: "6307", points: 50, category: "Dhikr" },
  { id: 198, title: "Honoring guests", desc: "Providing the best hospitality possible.", book: "Bukhari", num: "6135", points: 55, category: "Social" },
  { id: 199, title: "Avoiding Ghibah", desc: "Leaving a gathering where backbiting is happening.", book: "Muslim", num: "2589", points: 70, category: "Speech" },
  { id: 200, title: "Kindness to Orphans", desc: "Being gentle and supportive of those without parents.", book: "Bukhari", num: "6005", points: 120, category: "Social" },
  { id: 201, title: "Dua for mirrors", desc: "Saying 'Allahumma kama hassanta khalqi...'", book: "Ahmad", num: "24392", points: 20, category: "General" },
  { id: 202, title: "Removing harm", desc: "Picking up a stone or glass from the road.", book: "Bukhari", num: "2442", points: 40, category: "General" },
  { id: 203, title: "Feeding others", desc: "Giving part of your lunch to a coworker or friend.", book: "Bukhari", num: "12", points: 50, category: "Social" },
  { id: 204, title: "Smiling is Sadaqah", desc: "Meeting your brother with a cheerful face.", book: "Tirmidhi", num: "1956", points: 20, category: "Social" },
  { id: 205, title: "Lowering the gaze", desc: "Avoiding looking at things that don't concern you.", book: "Quran", num: "24:30", points: 80, category: "General" },
  { id: 206, title: "Truthful speech", desc: "Ensuring every word spoken is the truth.", book: "Muslim", num: "2607", points: 60, category: "Speech" },
  { id: 207, title: "Dua for debt", desc: "Reciting 'Allahumak-fini bi-halalika...'", book: "Tirmidhi", num: "3563", points: 45, category: "Dua" },
  { id: 208, title: "Fasting Mondays", desc: "Fasting tomorrow if it is a Monday.", book: "Muslim", num: "1162", points: 100, category: "Fasting" },
  { id: 209, title: "Fasting Thursdays", desc: "Fasting on the day deeds are presented.", book: "Tirmidhi", num: "747", points: 100, category: "Fasting" },
  { id: 210, title: "Using a Sutral", desc: "Placing an object in front during prayer.", book: "Bukhari", num: "494", points: 30, category: "Prayer" },
  { id: 211, title: "Using the Right Side", desc: "Sleeping on the right side as a habit.", book: "Bukhari", num: "247", points: 25, category: "Night" },
  { id: 212, title: "Dua for Sleep", desc: "Reciting 'Bismika Allahumma' before bed.", book: "Bukhari", num: "6312", points: 20, category: "Night" },
  { id: 213, title: "Tahajjud", desc: "Waking for the night prayer, even for 2 units.", book: "Bukhari", num: "1145", points: 150, category: "Night" },
  { id: 214, title: "Dua for Parents", desc: "Asking Allah to have mercy on them.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
  { id: 215, title: "Walking to Masjid", desc: "Walking instead of driving when possible.", book: "Bukhari", num: "662", points: 50, category: "Masjid" },
  { id: 216, title: "Greeting Neighbors", desc: "Checking in on the welfare of neighbors.", book: "Bukhari", num: "6016", points: 60, category: "Social" },
  { id: 217, title: "Kindness to Animals", desc: "Providing water for a thirsty animal.", book: "Bukhari", num: "2363", points: 45, category: "Social" },
  { id: 218, title: "Dua for Knowledge", desc: "Saying 'Rabbi zidni 'ilma'.", book: "Quran", num: "20:114", points: 30, category: "Dua" },
  { id: 219, title: "Prophetic Hygiene", desc: "Trimming nails on a Friday.", book: "Bukhari", num: "5891", points: 30, category: "General" },
  { id: 220, title: "Smiling to Siblings", desc: "Maintaining a cheerful attitude at home.", book: "Tirmidhi", num: "1956", points: 20, category: "Social" },
  { id: 221, title: "Dua for New Clothes", desc: "Thanking Allah for the garment.", book: "Abu Dawud", num: "4023", points: 25, category: "General" },
  { id: 222, title: "Honoring Guests", desc: "Serving guests with the best you have.", book: "Bukhari", num: "6135", points: 50, category: "Social" },
  { id: 223, title: "Truthful Trading", desc: "Being honest in any business transaction.", book: "Bukhari", num: "2079", points: 70, category: "General" },
  { id: 224, title: "Feeding the Hungry", desc: "Giving food to someone in need.", book: "Bukhari", num: "12", points: 80, category: "Social" },
  { id: 225, title: "Dua for Travel", desc: "Reciting the travel prayer when leaving.", book: "Muslim", num: "1342", points: 35, category: "Travel" },
  { id: 226, title: "Visiting Graves", desc: "Occasional visits to remember the hereafter.", book: "Muslim", num: "977", points: 40, category: "General" },
  { id: 227, title: "Gentle Speech", desc: "Avoiding harsh words in anger.", book: "Bukhari", num: "6035", points: 55, category: "Social" },
  { id: 228, title: "Dua for Rain", desc: "Praising Allah for the blessing of rain.", book: "Bukhari", num: "1032", points: 20, category: "Dua" },
  { id: 229, title: "Reciting Ayatul Kursi", desc: "Reciting it after every obligatory prayer.", book: "Nasa'i", num: "9928", points: 50, category: "Dhikr" },
  { id: 230, title: "Fasting White Days", desc: "Fasting the 13th, 14th, 15th of the month.", book: "Nasa'i", num: "2420", points: 150, category: "Fasting" },
  { id: 231, title: "Dua for Protection", desc: "Saying 'A'udhu bi-kalimatillah' at night.", book: "Muslim", num: "2708", points: 30, category: "Dua" },
  { id: 232, title: "Right Foot First", desc: "Wearing the right shoe before the left.", book: "Bukhari", num: "5855", points: 15, category: "General" },
  { id: 233, title: "Seeking Forgiveness", desc: "Saying 'Astaghfirullah' 100 times.", book: "Muslim", num: "2702", points: 60, category: "Dhikr" },
  { id: 234, title: "Giving Salaam", desc: "Greeting those you know and those you don't.", book: "Bukhari", num: "12", points: 40, category: "Social" },
  { id: 235, title: "The Siesta", desc: "A short midday nap to aid ibadah.", book: "Tabarani", num: "28", points: 30, category: "General" },
  { id: 236, title: "Honey for Shifa", desc: "Using honey for its medicinal benefits.", book: "Bukhari", num: "5677", points: 35, category: "Health" },
  { id: 237, title: "Black Seed", desc: "Using Habbatul Barakah in your diet.", book: "Bukhari", num: "5688", points: 35, category: "Health" },
  { id: 238, title: "Checking Shoes", desc: "Ensuring shoes are clean before wearing.", book: "Abu Dawud", num: "4139", points: 15, category: "General" },
  { id: 239, title: "Closing the Mouth", desc: "Covering the mouth when yawning.", book: "Muslim", num: "2995", points: 15, category: "General" },
  { id: 240, title: "Tahiyatul Wudu", desc: "2 units of prayer after every wudu.", book: "Bukhari", num: "160", points: 60, category: "Prayer" },
  { id: 241, title: "Dua for Parents", desc: "Praying 'Rabbir hamhuma kama rabbayani saghira'.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
  { id: 242, title: "Using Right Hand", desc: "Eating and drinking with the right hand.", book: "Muslim", num: "2020", points: 20, category: "General" },
  { id: 243, title: "Dua for Knowledge", desc: "Asking Allah for beneficial knowledge.", book: "Ibn Majah", num: "3843", points: 30, category: "Dua" },
  { id: 244, title: "Tahiyatul Masjid", desc: "Praying 2 units before sitting in any mosque.", book: "Bukhari", num: "444", points: 50, category: "Prayer" },
  { id: 245, title: "Closing Doors", desc: "Closing doors at night while mentioning Allah's name.", book: "Bukhari", num: "3304", points: 25, category: "Night" },
  { id: 246, title: "Dua for Entering Home", desc: "Greeting the family with Salaam even if alone.", book: "Abu Dawud", num: "5096", points: 30, category: "General" },
  { id: 247, title: "Avoiding Extravagance", desc: "Using only the necessary amount of water for Wudu.", book: "Ibn Majah", num: "425", points: 40, category: "General" },
  { id: 248, title: "Truthful Speech", desc: "Maintaining honesty even in small matters.", book: "Muslim", num: "2607", points: 60, category: "Speech" },
  { id: 249, title: "Dua for Guidance", desc: "Asking Allah for piety and contentment.", book: "Muslim", num: "2721", points: 45, category: "Dua" },
  { id: 250, title: "Kindness to Widows", desc: "Helping those who have lost their spouses.", book: "Bukhari", num: "5353", points: 100, category: "Social" },
  { id: 251, title: "Dua for Sleep", desc: "Reciting 'Bismika Allahumma' before sleeping.", book: "Bukhari", num: "6312", points: 20, category: "Night" },
  { id: 252, title: "Shaking out Shoes", desc: "Checking footwear for dirt or insects before wearing.", book: "Abu Dawud", num: "4139", points: 15, category: "General" },
  { id: 253, title: "Dua for Rain", desc: "Asking Allah for beneficial rain.", book: "Bukhari", num: "1013", points: 30, category: "Dua" },
  { id: 254, title: "Greeting Children", desc: "Giving Salaam to kids to encourage them.", book: "Muslim", num: "2168", points: 25, category: "Social" },
  { id: 255, title: "Dua after Eating", desc: "Praising Allah after finishing a meal.", book: "Tirmidhi", num: "3458", points: 20, category: "Food" },
  { id: 256, title: "Honoring Neighbors", desc: "Not bothering neighbors with loud noise or harm.", book: "Bukhari", num: "6016", points: 60, category: "Social" },
  { id: 257, title: "Dua for Travel", desc: "Reciting the prayer for safety on journeys.", book: "Muslim", num: "1342", points: 35, category: "Travel" },
  { id: 258, title: "Smiling is Charity", desc: "Meeting others with a cheerful countenance.", book: "Tirmidhi", num: "1956", points: 20, category: "Social" },
  { id: 259, title: "Lowering the Gaze", desc: "Avoiding looking at things that are forbidden.", book: "Quran", num: "24:30", points: 80, category: "General" },
  { id: 260, title: "Seeking Forgiveness", desc: "Saying 'Astaghfirullah' 70-100 times daily.", book: "Bukhari", num: "6307", points: 50, category: "Dhikr" },
  { id: 261, title: "Walking to Masjid", desc: "Taking steps to the mosque for reward.", book: "Bukhari", num: "662", points: 50, category: "Masjid" },
  { id: 262, title: "Dua for Protection", desc: "Asking for safety from all harm at night.", book: "Muslim", num: "2708", points: 30, category: "Dua" },
  { id: 263, title: "Right Side Sleeping", desc: "Resting on the right side as per sunnah.", book: "Bukhari", num: "247", points: 25, category: "Night" },
  { id: 264, title: "Dua for Sickness", desc: "Reciting 'Adhhibil-bas' for someone ill.", book: "Bukhari", num: "5675", points: 50, category: "Dua" },
  { id: 265, title: "Using the Miswak", desc: "Ensuring oral hygiene before every prayer.", book: "Muslim", num: "252", points: 30, category: "General" },
  { id: 266, title: "Dua for the Market", desc: "Reciting the Zikr when entering a mall.", book: "Tirmidhi", num: "3428", points: 80, category: "Dua" },
  { id: 267, title: "Honoring the Guest", desc: "Believing in Allah by honoring the visitor.", book: "Bukhari", num: "6135", points: 55, category: "Social" },
  { id: 268, title: "Dua for Parents", desc: "Supplicating for them after every Fard prayer.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
  { id: 269, title: "Checking for Pins", desc: "Checking shoes for sharp objects before wearing.", book: "Abu Dawud", num: "4139", points: 10, category: "General" },
  { id: 270, title: "Gentle Correction", desc: "Advising others with kindness and privacy.", book: "Bukhari", num: "6035", points: 45, category: "Speech" },
  { id: 271, title: "Dua for Anxiety", desc: "Asking Allah for relief from distress.", book: "Bukhari", num: "2893", points: 40, category: "Dua" },
  { id: 272, title: "Removing Obstacles", desc: "Clearing a branch or stone from the path.", book: "Muslim", num: "1914", points: 40, category: "General" },
  { id: 273, title: "Dua for Morning", desc: "Thanking Allah for the gift of life at dawn.", book: "Bukhari", num: "6312", points: 25, category: "Dhikr" },
  { id: 274, title: "Fasting Mondays", desc: "Observing the Prophetic fast on Monday.", book: "Muslim", num: "1162", points: 100, category: "Fasting" },
  { id: 275, title: "Dua for Safety", desc: "Reciting the morning and evening protection prayers.", book: "Tirmidhi", num: "3388", points: 35, category: "Dua" },
  { id: 276, title: "Planting a Tree", desc: "Acting on the reward for ongoing charity.", book: "Bukhari", num: "2320", points: 80, category: "General" },
  { id: 277, title: "Dua after Wudu", desc: "Reciting the Shahadah after finishing ablution.", book: "Muslim", num: "234", points: 35, category: "Prayer" },
  { id: 278, title: "Fasting Thursdays", desc: "Observing the fast when deeds are presented.", book: "Tirmidhi", num: "747", points: 100, category: "Fasting" },
  { id: 279, title: "Dua for New Moon", desc: "Praying for security at the start of a month.", book: "Tirmidhi", num: "3451", points: 40, category: "Dua" },
  { id: 280, title: "Sharing Food", desc: "Feeding a neighbor or a friend.", book: "Muslim", num: "2625", points: 50, category: "Social" },
  { id: 281, title: "Dua for Protection", desc: "Saying 'Bismillahil-ladhi la yadurru'.", book: "Tirmidhi", num: "3388", points: 35, category: "Dua" },
  { id: 282, title: "Sitting While Drinking", desc: "Not drinking while standing as per sunnah.", book: "Muslim", num: "2024", points: 20, category: "Food" },
  { id: 283, title: "Dua for Mirrors", desc: "Asking Allah for beautiful character.", book: "Ahmad", num: "24392", points: 20, category: "General" },
  { id: 284, title: "Honoring Elderly", desc: "Showing respect to those older than you.", book: "Tirmidhi", num: "1915", points: 55, category: "Social" },
  { id: 285, title: "Dua for Debt", desc: "Asking Allah for relief from financial burden.", book: "Tirmidhi", num: "3563", points: 45, category: "Dua" },
  { id: 286, title: "Greeting Everyone", desc: "Giving Salaam to friends and strangers.", book: "Bukhari", num: "12", points: 40, category: "Social" },
  { id: 287, title: "Dua for Parents", desc: "Praying for them after every Salah.", book: "Quran", num: "17:24", points: 40, category: "Dua" },
  { id: 288, title: "Friday Ghusl", desc: "Performing the ritual bath for Jumu'ah.", book: "Bukhari", num: "877", points: 60, category: "Friday" },
  { id: 289, title: "Dua after Prayer", desc: "Reciting 'SubhanAllah, Alhamdulillah, Allahu Akbar'.", book: "Muslim", num: "597", points: 45, category: "Dhikr" },
  { id: 290, title: "Tahajjud Prayer", desc: "Waking up for Qiyam-ul-Layl.", book: "Bukhari", num: "1145", points: 150, category: "Prayer" },
  { id: 291, title: "Dua for Rain", desc: "Asking for water during dry seasons.", book: "Bukhari", num: "1013", points: 30, category: "Dua" },
  { id: 292, title: "Checking for Insects", desc: "Dusting the bed before lying down.", book: "Bukhari", num: "6320", points: 20, category: "Night" },
  { id: 293, title: "Dua for Strength", desc: "Asking Allah for help in all matters.", book: "Muslim", num: "2664", points: 35, category: "Dua" },
  { id: 294, title: "Feeding Animals", desc: "Showing mercy to the creation of Allah.", book: "Bukhari", num: "2363", points: 45, category: "Social" },
  { id: 295, title: "Dua for the Ummah", desc: "Supplicating for the welfare of all Muslims.", book: "Tabarani", num: "2118", points: 50, category: "Dua" },
  { id: 296, title: "Speaking Good", desc: "Talking with purpose or remaining silent.", book: "Bukhari", num: "6018", points: 50, category: "Speech" },
  { id: 297, title: "Dua for Safety", desc: "Asking for Aafiyah in this world and next.", book: "Tirmidhi", num: "3514", points: 40, category: "Dua" },
  { id: 298, title: "Greeting Neighbors", desc: "Keeping a good relationship with those next door.", book: "Bukhari", num: "6016", points: 60, category: "Social" },
  { id: 299, title: "Dua for Parents", desc: "Making Istighfar for parents.", book: "Ibn Majah", num: "3660", points: 45, category: "Dua" },
  { id: 300, title: "Completing 300", desc: "Commitment to reviving the Sunnah daily.", book: "General", num: "300", points: 200, category: "Achievement" }
    ];